# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://breo.beds.ac.uk/?new_loc=%2Fultra%2Fcourse'
      - name: JUNIT Test Report Tool
        # You may pin to the exact commit or the version.
        # uses: JohnMeyerhoff/JunitAnnotations@0b633bca6b09f3301a6fa678310c53e754e7cf16
        uses: JohnMeyeroff/JunitAnnotations@v1.2.0
        with:
          # [Path] The location of the folder(s) containing your code files
          source_dir: A1Amana/Connection
