name: Dastardly CI/CD

on: [push]

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Dastardly
      run: |
        docker run --user $(id -u) --rm -v $(pwd):/dastardly -e \
        BURP_START_URL=https://your-web-application-url -e \
        BURP_REPORT_FILE_PATH=/dastardly/dastardly-report.xml \
        public.ecr.aws/portswigger/dastardly:latest
